### Get request to greet
GET http://localhost:8888/user/greet/example HTTP/1.1

### Get request to greet to nobody
GET http://localhost:8888/user/greet HTTP/1.1

### Post username and password
POST  http://localhost:8888/user/login HTTP/1.1
User-Agent: vscode-restclient
Content-Type: application/json

{
    "username": "example",
    "password": "example"
}

### Post an empty login
POST  http://localhost:8888/user/login HTTP/1.1
User-Agent: vscode-restclient


### Post an error json
POST  http://localhost:8888/user/login HTTP/1.1
User-Agent: vscode-restclient
Content-Type: application/json

{
    "username": "example1",
    "password": "example1"
}